apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-gateway
  template:
    metadata:
      labels:
        app: payment-gateway
    spec:
      containers:
        - name: payment-gateway
          image: henryarrovin/payment-gateway:latest
          ports:
            - containerPort: 8081
              name: http
            - containerPort: 50052
              name: grpc
          envFrom:
            - configMapRef:
                name: payment-config
            - secretRef:
                name: payment-secrets
          env:
            - name: PAYMENT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: PAYMENT_DB_PASSWORD
            - name: PAYMENT_AUTH_GRPC_CANONICAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: PAYMENT_AUTH_GRPC_CANONICAL_SECRET
          volumeMounts:
            - name: logs
              mountPath: /apps/logs
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: logs-pvc