apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth
type: Opaque
stringData:
  AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
  AUTH_JWT_ACCESS_SECRET: ${AUTH_JWT_ACCESS_SECRET}
  AUTH_JWT_REFRESH_SECRET: ${AUTH_JWT_REFRESH_SECRET}
  AUTH_JWT_CANONICAL_SECRET: ${AUTH_JWT_CANONICAL_SECRET}

---

apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: auth
type: Opaque
stringData:
  PAYMENT_DB_PASSWORD: ${PAYMENT_DB_PASSWORD}
  PAYMENT_AUTH_GRPC_CANONICAL_SECRET: ${PAYMENT_AUTH_GRPC_CANONICAL_SECRET}