// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go.uber.org/zap"
	"payment-gateway/config"
	"payment-gateway/data"
	"payment-gateway/external/razorpay"
	"payment-gateway/handlers"
	"payment-gateway/services"
)

// Injectors from wire.go:

func InitializeContainer(cfgFile string, logger *zap.Logger) (*handlers.PaymentHandler, func(), error) {
	configConfig, err := config.Load(cfgFile)
	if err != nil {
		return nil, nil, err
	}
	db, err := data.NewDB(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	orderRepository := data.NewOrderRepository(db)
	paymentRepository := data.NewPaymentRepository(db)
	permissionRepository := data.NewPermissionRepository(db)
	providerRepository := data.NewProviderRepository(db)
	adapter := provideRazorpayAdapter(logger)
	paymentService := services.NewPaymentService(orderRepository, paymentRepository, permissionRepository, providerRepository, adapter, logger)
	paymentHandler := handlers.NewPaymentHandler(paymentService, logger)
	return paymentHandler, func() {
	}, nil
}

// wire.go:

func provideRazorpayAdapter(logger *zap.Logger) razorpay.Adapter {
	return razorpay.NewAdapter(logger)
}
